package com.konfigthis.client;

import com.konfigthis.client.api.AchTransactionsApi;
import com.konfigthis.client.api.BankAccountsApi;
import com.konfigthis.client.api.CompaniesApi;
import com.konfigthis.client.api.CompanyBenefitsApi;
import com.konfigthis.client.api.CompanyFormsApi;
import com.konfigthis.client.api.ContractorFormsApi;
import com.konfigthis.client.api.ContractorPaymentMethodApi;
import com.konfigthis.client.api.ContractorPaymentsApi;
import com.konfigthis.client.api.ContractorsApi;
import com.konfigthis.client.api.DepartmentsApi;
import com.konfigthis.client.api.EarningTypesApi;
import com.konfigthis.client.api.EmployeeAddressesApi;
import com.konfigthis.client.api.EmployeeBenefitsApi;
import com.konfigthis.client.api.EmployeeEmploymentsApi;
import com.konfigthis.client.api.EmployeeFormsApi;
import com.konfigthis.client.api.EmployeePaymentMethodApi;
import com.konfigthis.client.api.EmployeeTaxSetupApi;
import com.konfigthis.client.api.EmployeesApi;
import com.konfigthis.client.api.EventsApi;
import com.konfigthis.client.api.ExternalPayrollsApi;
import com.konfigthis.client.api.FederalTaxDetailsApi;
import com.konfigthis.client.api.FlowsApi;
import com.konfigthis.client.api.GarnishmentsApi;
import com.konfigthis.client.api.GeneratedDocumentsApi;
import com.konfigthis.client.api.HolidayPayPoliciesApi;
import com.konfigthis.client.api.IndustrySelectionApi;
import com.konfigthis.client.api.IntrospectionApi;
import com.konfigthis.client.api.InvoicesApi;
import com.konfigthis.client.api.JobsAndCompensationsApi;
import com.konfigthis.client.api.LocationsApi;
import com.konfigthis.client.api.NotificationsApi;
import com.konfigthis.client.api.PaySchedulesApi;
import com.konfigthis.client.api.PaymentConfigsApi;
import com.konfigthis.client.api.PayrollsApi;
import com.konfigthis.client.api.RecoveryCasesApi;
import com.konfigthis.client.api.SignatoriesApi;
import com.konfigthis.client.api.TaxRequirementsApi;
import com.konfigthis.client.api.TimeOffPoliciesApi;
import com.konfigthis.client.api.WebhooksApi;

public class GustoEmbeddedPayroll {
    private ApiClient apiClient;
    public final AchTransactionsApi achTransactions;
    public final BankAccountsApi bankAccounts;
    public final CompaniesApi companies;
    public final CompanyBenefitsApi companyBenefits;
    public final CompanyFormsApi companyForms;
    public final ContractorFormsApi contractorForms;
    public final ContractorPaymentMethodApi contractorPaymentMethod;
    public final ContractorPaymentsApi contractorPayments;
    public final ContractorsApi contractors;
    public final DepartmentsApi departments;
    public final EarningTypesApi earningTypes;
    public final EmployeeAddressesApi employeeAddresses;
    public final EmployeeBenefitsApi employeeBenefits;
    public final EmployeeEmploymentsApi employeeEmployments;
    public final EmployeeFormsApi employeeForms;
    public final EmployeePaymentMethodApi employeePaymentMethod;
    public final EmployeeTaxSetupApi employeeTaxSetup;
    public final EmployeesApi employees;
    public final EventsApi events;
    public final ExternalPayrollsApi externalPayrolls;
    public final FederalTaxDetailsApi federalTaxDetails;
    public final FlowsApi flows;
    public final GarnishmentsApi garnishments;
    public final GeneratedDocumentsApi generatedDocuments;
    public final HolidayPayPoliciesApi holidayPayPolicies;
    public final IndustrySelectionApi industrySelection;
    public final IntrospectionApi introspection;
    public final InvoicesApi invoices;
    public final JobsAndCompensationsApi jobsAndCompensations;
    public final LocationsApi locations;
    public final NotificationsApi notifications;
    public final PaySchedulesApi paySchedules;
    public final PaymentConfigsApi paymentConfigs;
    public final PayrollsApi payrolls;
    public final RecoveryCasesApi recoveryCases;
    public final SignatoriesApi signatories;
    public final TaxRequirementsApi taxRequirements;
    public final TimeOffPoliciesApi timeOffPolicies;
    public final WebhooksApi webhooks;

    public GustoEmbeddedPayroll() {
        this(null);
    }

    public GustoEmbeddedPayroll(Configuration configuration) {
        this.apiClient = new ApiClient(null, configuration);
        this.achTransactions = new AchTransactionsApi(this.apiClient);
        this.bankAccounts = new BankAccountsApi(this.apiClient);
        this.companies = new CompaniesApi(this.apiClient);
        this.companyBenefits = new CompanyBenefitsApi(this.apiClient);
        this.companyForms = new CompanyFormsApi(this.apiClient);
        this.contractorForms = new ContractorFormsApi(this.apiClient);
        this.contractorPaymentMethod = new ContractorPaymentMethodApi(this.apiClient);
        this.contractorPayments = new ContractorPaymentsApi(this.apiClient);
        this.contractors = new ContractorsApi(this.apiClient);
        this.departments = new DepartmentsApi(this.apiClient);
        this.earningTypes = new EarningTypesApi(this.apiClient);
        this.employeeAddresses = new EmployeeAddressesApi(this.apiClient);
        this.employeeBenefits = new EmployeeBenefitsApi(this.apiClient);
        this.employeeEmployments = new EmployeeEmploymentsApi(this.apiClient);
        this.employeeForms = new EmployeeFormsApi(this.apiClient);
        this.employeePaymentMethod = new EmployeePaymentMethodApi(this.apiClient);
        this.employeeTaxSetup = new EmployeeTaxSetupApi(this.apiClient);
        this.employees = new EmployeesApi(this.apiClient);
        this.events = new EventsApi(this.apiClient);
        this.externalPayrolls = new ExternalPayrollsApi(this.apiClient);
        this.federalTaxDetails = new FederalTaxDetailsApi(this.apiClient);
        this.flows = new FlowsApi(this.apiClient);
        this.garnishments = new GarnishmentsApi(this.apiClient);
        this.generatedDocuments = new GeneratedDocumentsApi(this.apiClient);
        this.holidayPayPolicies = new HolidayPayPoliciesApi(this.apiClient);
        this.industrySelection = new IndustrySelectionApi(this.apiClient);
        this.introspection = new IntrospectionApi(this.apiClient);
        this.invoices = new InvoicesApi(this.apiClient);
        this.jobsAndCompensations = new JobsAndCompensationsApi(this.apiClient);
        this.locations = new LocationsApi(this.apiClient);
        this.notifications = new NotificationsApi(this.apiClient);
        this.paySchedules = new PaySchedulesApi(this.apiClient);
        this.paymentConfigs = new PaymentConfigsApi(this.apiClient);
        this.payrolls = new PayrollsApi(this.apiClient);
        this.recoveryCases = new RecoveryCasesApi(this.apiClient);
        this.signatories = new SignatoriesApi(this.apiClient);
        this.taxRequirements = new TaxRequirementsApi(this.apiClient);
        this.timeOffPolicies = new TimeOffPoliciesApi(this.apiClient);
        this.webhooks = new WebhooksApi(this.apiClient);
    }

}
