/*
 * Gusto API
 * Welcome to Gusto's Embedded Payroll API documentation!
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: developer@gusto.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BenefitTypeRequirementsEmployeeDeduction;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BenefitTypeRequirements
 */
public class BenefitTypeRequirementsTest {
    private final BenefitTypeRequirements model = new BenefitTypeRequirements();

    /**
     * Model tests for BenefitTypeRequirements
     */
    @Test
    public void testBenefitTypeRequirements() {
        // TODO: test BenefitTypeRequirements
    }

    /**
     * Test the property 'employeeDeduction'
     */
    @Test
    public void employeeDeductionTest() {
        // TODO: test employeeDeduction
    }

    /**
     * Test the property 'contribution'
     */
    @Test
    public void contributionTest() {
        // TODO: test contribution
    }

    /**
     * Test the property 'deductAsPercentage'
     */
    @Test
    public void deductAsPercentageTest() {
        // TODO: test deductAsPercentage
    }

    /**
     * Test the property 'catchUp'
     */
    @Test
    public void catchUpTest() {
        // TODO: test catchUp
    }

    /**
     * Test the property 'limitOption'
     */
    @Test
    public void limitOptionTest() {
        // TODO: test limitOption
    }

    /**
     * Test the property 'companyContributionAnnualMaximum'
     */
    @Test
    public void companyContributionAnnualMaximumTest() {
        // TODO: test companyContributionAnnualMaximum
    }

    /**
     * Test the property 'coverageSalaryMultiplier'
     */
    @Test
    public void coverageSalaryMultiplierTest() {
        // TODO: test coverageSalaryMultiplier
    }

    /**
     * Test the property 'coverageAmount'
     */
    @Test
    public void coverageAmountTest() {
        // TODO: test coverageAmount
    }

}
