/*
 * Gusto API
 * Welcome to Gusto's Embedded Payroll API documentation!
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: developer@gusto.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ContractorAddress;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Contractor
 */
public class ContractorTest {
    private final Contractor model = new Contractor();

    /**
     * Model tests for Contractor
     */
    @Test
    public void testContractor() {
        // TODO: test Contractor
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'companyUuid'
     */
    @Test
    public void companyUuidTest() {
        // TODO: test companyUuid
    }

    /**
     * Test the property 'wageType'
     */
    @Test
    public void wageTypeTest() {
        // TODO: test wageType
    }

    /**
     * Test the property 'isActive'
     */
    @Test
    public void isActiveTest() {
        // TODO: test isActive
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'middleInitial'
     */
    @Test
    public void middleInitialTest() {
        // TODO: test middleInitial
    }

    /**
     * Test the property 'businessName'
     */
    @Test
    public void businessNameTest() {
        // TODO: test businessName
    }

    /**
     * Test the property 'ein'
     */
    @Test
    public void einTest() {
        // TODO: test ein
    }

    /**
     * Test the property 'hasEin'
     */
    @Test
    public void hasEinTest() {
        // TODO: test hasEin
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'hourlyRate'
     */
    @Test
    public void hourlyRateTest() {
        // TODO: test hourlyRate
    }

    /**
     * Test the property 'fileNewHireReport'
     */
    @Test
    public void fileNewHireReportTest() {
        // TODO: test fileNewHireReport
    }

    /**
     * Test the property 'workState'
     */
    @Test
    public void workStateTest() {
        // TODO: test workState
    }

    /**
     * Test the property 'onboarded'
     */
    @Test
    public void onboardedTest() {
        // TODO: test onboarded
    }

    /**
     * Test the property 'onboardingStatus'
     */
    @Test
    public void onboardingStatusTest() {
        // TODO: test onboardingStatus
    }

}
