/*
 * Gusto API
 * Welcome to Gusto's Embedded Payroll API documentation!
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: developer@gusto.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ExternalPayrollExternalPayrollItemsInnerBenefitsInner;
import com.konfigthis.client.model.ExternalPayrollExternalPayrollItemsInnerEarningsInner;
import com.konfigthis.client.model.ExternalPayrollExternalPayrollItemsInnerTaxesInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ExternalPayrollExternalPayrollItemsInner
 */
public class ExternalPayrollExternalPayrollItemsInnerTest {
    private final ExternalPayrollExternalPayrollItemsInner model = new ExternalPayrollExternalPayrollItemsInner();

    /**
     * Model tests for ExternalPayrollExternalPayrollItemsInner
     */
    @Test
    public void testExternalPayrollExternalPayrollItemsInner() {
        // TODO: test ExternalPayrollExternalPayrollItemsInner
    }

    /**
     * Test the property 'employeeUuid'
     */
    @Test
    public void employeeUuidTest() {
        // TODO: test employeeUuid
    }

    /**
     * Test the property 'earnings'
     */
    @Test
    public void earningsTest() {
        // TODO: test earnings
    }

    /**
     * Test the property 'benefits'
     */
    @Test
    public void benefitsTest() {
        // TODO: test benefits
    }

    /**
     * Test the property 'taxes'
     */
    @Test
    public void taxesTest() {
        // TODO: test taxes
    }

}
