/*
 * Gusto API
 * Welcome to Gusto's Embedded Payroll API documentation!
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: developer@gusto.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GarnishmentsUpdateGarnishmentRequest
 */
public class GarnishmentsUpdateGarnishmentRequestTest {
    private final GarnishmentsUpdateGarnishmentRequest model = new GarnishmentsUpdateGarnishmentRequest();

    /**
     * Model tests for GarnishmentsUpdateGarnishmentRequest
     */
    @Test
    public void testGarnishmentsUpdateGarnishmentRequest() {
        // TODO: test GarnishmentsUpdateGarnishmentRequest
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'courtOrdered'
     */
    @Test
    public void courtOrderedTest() {
        // TODO: test courtOrdered
    }

    /**
     * Test the property 'times'
     */
    @Test
    public void timesTest() {
        // TODO: test times
    }

    /**
     * Test the property 'recurring'
     */
    @Test
    public void recurringTest() {
        // TODO: test recurring
    }

    /**
     * Test the property 'annualMaximum'
     */
    @Test
    public void annualMaximumTest() {
        // TODO: test annualMaximum
    }

    /**
     * Test the property 'payPeriodMaximum'
     */
    @Test
    public void payPeriodMaximumTest() {
        // TODO: test payPeriodMaximum
    }

    /**
     * Test the property 'deductAsPercentage'
     */
    @Test
    public void deductAsPercentageTest() {
        // TODO: test deductAsPercentage
    }

}
