/*
 * Gusto API
 * Welcome to Gusto's Embedded Payroll API documentation!
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: developer@gusto.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.FlsaStatusType;
import com.konfigthis.client.model.JobsAndCompensationsCreateCompensationRequestMinimumWagesInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for JobsAndCompensationsUpdateCompensationRequest
 */
public class JobsAndCompensationsUpdateCompensationRequestTest {
    private final JobsAndCompensationsUpdateCompensationRequest model = new JobsAndCompensationsUpdateCompensationRequest();

    /**
     * Model tests for JobsAndCompensationsUpdateCompensationRequest
     */
    @Test
    public void testJobsAndCompensationsUpdateCompensationRequest() {
        // TODO: test JobsAndCompensationsUpdateCompensationRequest
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'rate'
     */
    @Test
    public void rateTest() {
        // TODO: test rate
    }

    /**
     * Test the property 'paymentUnit'
     */
    @Test
    public void paymentUnitTest() {
        // TODO: test paymentUnit
    }

    /**
     * Test the property 'flsaStatus'
     */
    @Test
    public void flsaStatusTest() {
        // TODO: test flsaStatus
    }

    /**
     * Test the property 'adjustForMinimumWage'
     */
    @Test
    public void adjustForMinimumWageTest() {
        // TODO: test adjustForMinimumWage
    }

    /**
     * Test the property 'minimumWages'
     */
    @Test
    public void minimumWagesTest() {
        // TODO: test minimumWages
    }

}
