/*
 * Gusto API
 * Welcome to Gusto's Embedded Payroll API documentation!
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: developer@gusto.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PayScheduleAssignmentBodyEmployeesInner
 */
public class PayScheduleAssignmentBodyEmployeesInnerTest {
    private final PayScheduleAssignmentBodyEmployeesInner model = new PayScheduleAssignmentBodyEmployeesInner();

    /**
     * Model tests for PayScheduleAssignmentBodyEmployeesInner
     */
    @Test
    public void testPayScheduleAssignmentBodyEmployeesInner() {
        // TODO: test PayScheduleAssignmentBodyEmployeesInner
    }

    /**
     * Test the property 'employeeUuid'
     */
    @Test
    public void employeeUuidTest() {
        // TODO: test employeeUuid
    }

    /**
     * Test the property 'payScheduleUuid'
     */
    @Test
    public void payScheduleUuidTest() {
        // TODO: test payScheduleUuid
    }

}
