/*
 * Gusto API
 * Welcome to Gusto's Embedded Payroll API documentation!
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: developer@gusto.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TaxLiabilitiesSelectionsPossibleLiabilities
 */
public class TaxLiabilitiesSelectionsPossibleLiabilitiesTest {
    private final TaxLiabilitiesSelectionsPossibleLiabilities model = new TaxLiabilitiesSelectionsPossibleLiabilities();

    /**
     * Model tests for TaxLiabilitiesSelectionsPossibleLiabilities
     */
    @Test
    public void testTaxLiabilitiesSelectionsPossibleLiabilities() {
        // TODO: test TaxLiabilitiesSelectionsPossibleLiabilities
    }

    /**
     * Test the property 'liabilityAmount'
     */
    @Test
    public void liabilityAmountTest() {
        // TODO: test liabilityAmount
    }

    /**
     * Test the property 'payrollCheckDate'
     */
    @Test
    public void payrollCheckDateTest() {
        // TODO: test payrollCheckDate
    }

    /**
     * Test the property 'externalPayrollUuid'
     */
    @Test
    public void externalPayrollUuidTest() {
        // TODO: test externalPayrollUuid
    }

}
