/*
 * Gusto API
 * Welcome to Gusto's Embedded Payroll API documentation!
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: developer@gusto.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The payment schedule tax rate the payroll is based on. Only included for off-cycle payrolls.
 */
@JsonAdapter(PayrollWithholdingPayPeriodType.Adapter.class)public enum PayrollWithholdingPayPeriodType {
  
  EVERY_WEEK("Every week"),
  
  EVERY_OTHER_WEEK("Every other week"),
  
  TWICE_PER_MONTH("Twice per month"),
  
  MONTHLY("Monthly"),
  
  QUARTERLY("Quarterly"),
  
  SEMIANNUALLY("Semiannually"),
  
  ANNUALLY("Annually");

  private String value;

  PayrollWithholdingPayPeriodType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PayrollWithholdingPayPeriodType fromValue(String value) {
    for (PayrollWithholdingPayPeriodType b : PayrollWithholdingPayPeriodType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<PayrollWithholdingPayPeriodType> {
    @Override
    public void write(final JsonWriter jsonWriter, final PayrollWithholdingPayPeriodType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PayrollWithholdingPayPeriodType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PayrollWithholdingPayPeriodType.fromValue(value);
    }
  }
}

