/*
 * Gusto API
 * Welcome to Gusto's Embedded Payroll API documentation!
 *
 * The version of the OpenAPI document: 2024-03-01
 * Contact: developer@gusto.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TaxLiabilitiesSelectionsPossibleLiabilities;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * The representation of tax liabilities selections.
 */
@ApiModel(description = "The representation of tax liabilities selections.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class TaxLiabilitiesSelections {
  public static final String SERIALIZED_NAME_TAX_ID = "tax_id";
  @SerializedName(SERIALIZED_NAME_TAX_ID)
  private Integer taxId;

  public static final String SERIALIZED_NAME_TAX_NAME = "tax_name";
  @SerializedName(SERIALIZED_NAME_TAX_NAME)
  private String taxName;

  public static final String SERIALIZED_NAME_LAST_UNPAID_EXTERNAL_PAYROLL_UUID = "last_unpaid_external_payroll_uuid";
  @SerializedName(SERIALIZED_NAME_LAST_UNPAID_EXTERNAL_PAYROLL_UUID)
  private String lastUnpaidExternalPayrollUuid;

  public static final String SERIALIZED_NAME_POSSIBLE_LIABILITIES = "possible_liabilities";
  @SerializedName(SERIALIZED_NAME_POSSIBLE_LIABILITIES)
  private TaxLiabilitiesSelectionsPossibleLiabilities possibleLiabilities;

  public TaxLiabilitiesSelections() {
  }

  
  public TaxLiabilitiesSelections(
     Integer taxId, 
     String taxName, 
     String lastUnpaidExternalPayrollUuid
  ) {
    this();
    this.taxId = taxId;
    this.taxName = taxName;
    this.lastUnpaidExternalPayrollUuid = lastUnpaidExternalPayrollUuid;
  }

   /**
   * The ID of the tax.
   * @return taxId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "The ID of the tax.")

  public Integer getTaxId() {
    return taxId;
  }




   /**
   * The name of the tax.
   * @return taxName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Federal Income Tax", value = "The name of the tax.")

  public String getTaxName() {
    return taxName;
  }




   /**
   * The UUID of last unpaid external payroll.
   * @return lastUnpaidExternalPayrollUuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The UUID of last unpaid external payroll.")

  public String getLastUnpaidExternalPayrollUuid() {
    return lastUnpaidExternalPayrollUuid;
  }




  public TaxLiabilitiesSelections possibleLiabilities(TaxLiabilitiesSelectionsPossibleLiabilities possibleLiabilities) {
    
    
    
    
    this.possibleLiabilities = possibleLiabilities;
    return this;
  }

   /**
   * Get possibleLiabilities
   * @return possibleLiabilities
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TaxLiabilitiesSelectionsPossibleLiabilities getPossibleLiabilities() {
    return possibleLiabilities;
  }


  public void setPossibleLiabilities(TaxLiabilitiesSelectionsPossibleLiabilities possibleLiabilities) {
    
    
    
    this.possibleLiabilities = possibleLiabilities;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the TaxLiabilitiesSelections instance itself
   */
  public TaxLiabilitiesSelections putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaxLiabilitiesSelections taxLiabilitiesSelections = (TaxLiabilitiesSelections) o;
    return Objects.equals(this.taxId, taxLiabilitiesSelections.taxId) &&
        Objects.equals(this.taxName, taxLiabilitiesSelections.taxName) &&
        Objects.equals(this.lastUnpaidExternalPayrollUuid, taxLiabilitiesSelections.lastUnpaidExternalPayrollUuid) &&
        Objects.equals(this.possibleLiabilities, taxLiabilitiesSelections.possibleLiabilities)&&
        Objects.equals(this.additionalProperties, taxLiabilitiesSelections.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(taxId, taxName, lastUnpaidExternalPayrollUuid, possibleLiabilities, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaxLiabilitiesSelections {\n");
    sb.append("    taxId: ").append(toIndentedString(taxId)).append("\n");
    sb.append("    taxName: ").append(toIndentedString(taxName)).append("\n");
    sb.append("    lastUnpaidExternalPayrollUuid: ").append(toIndentedString(lastUnpaidExternalPayrollUuid)).append("\n");
    sb.append("    possibleLiabilities: ").append(toIndentedString(possibleLiabilities)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("tax_id");
    openapiFields.add("tax_name");
    openapiFields.add("last_unpaid_external_payroll_uuid");
    openapiFields.add("possible_liabilities");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to TaxLiabilitiesSelections
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!TaxLiabilitiesSelections.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TaxLiabilitiesSelections is not found in the empty JSON string", TaxLiabilitiesSelections.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("tax_name") != null && !jsonObj.get("tax_name").isJsonNull()) && !jsonObj.get("tax_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tax_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tax_name").toString()));
      }
      if (!jsonObj.get("last_unpaid_external_payroll_uuid").isJsonNull() && (jsonObj.get("last_unpaid_external_payroll_uuid") != null && !jsonObj.get("last_unpaid_external_payroll_uuid").isJsonNull()) && !jsonObj.get("last_unpaid_external_payroll_uuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `last_unpaid_external_payroll_uuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("last_unpaid_external_payroll_uuid").toString()));
      }
      // validate the optional field `possible_liabilities`
      if (jsonObj.get("possible_liabilities") != null && !jsonObj.get("possible_liabilities").isJsonNull()) {
        TaxLiabilitiesSelectionsPossibleLiabilities.validateJsonObject(jsonObj.getAsJsonObject("possible_liabilities"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TaxLiabilitiesSelections.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TaxLiabilitiesSelections' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TaxLiabilitiesSelections> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TaxLiabilitiesSelections.class));

       return (TypeAdapter<T>) new TypeAdapter<TaxLiabilitiesSelections>() {
           @Override
           public void write(JsonWriter out, TaxLiabilitiesSelections value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public TaxLiabilitiesSelections read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             TaxLiabilitiesSelections instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TaxLiabilitiesSelections given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TaxLiabilitiesSelections
  * @throws IOException if the JSON string is invalid with respect to TaxLiabilitiesSelections
  */
  public static TaxLiabilitiesSelections fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TaxLiabilitiesSelections.class);
  }

 /**
  * Convert an instance of TaxLiabilitiesSelections to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

